spring:
  datasource:
    dynamic:
      hikari:
        connection-test-query: SELECT 1
      primary: master
      datasource:
        master:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/timewatcher?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8&connectTimeout=3000
          username: "root"
          password: "root"
          hikari:
            max-pool-size: 10
            min-idle: 5
